---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: my-public-crossplane-subnet1
  labels:
    vpc: my-basic-crossplane-vpc
    publicOrPrivate: 'public'
    availabilityZone: eu-west-3a
spec:
  forProvider:
    region: eu-west-3
    # Do Stuff here
    tags:
    - key: Name
      value: my-public-crossplane-subnet1
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: my-public-crossplane-subnet2
  labels:
    vpc: my-basic-crossplane-vpc
    publicOrPrivate: 'public'
    availabilityZone: eu-west-3b
spec:
  forProvider:
    region: eu-west-3
    # Do Stuff here
    tags:
    - key: Name
      value: my-public-crossplane-subnet2