apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  name: {{ include "vpc.fullname" . }}
  labels:
    {{- include "vpc.labels" . | nindent 4 }}
spec:
  providerConfigRef:
    name: {{ .Values.providerConfigName }}
  forProvider:
    region: {{ .Values.region }}
    vpcIdRef:
      name: {{ include "vpc.fullname" . }}
    tags:
    - key: Name
      value: {{ include "vpc.fullname" . }}