apiVersion: ec2.aws.crossplane.io/v1beta1
kind: InternetGateway
metadata:
  name: my-basic-crossplane-igw
  labels:
    stack: crossplane-demo
spec:
  forProvider:
    region: eu-west-3
    vpcIdRef:
      name: my-basic-crossplane-vpc
    tags:
    - key: Name
      value: my-basic-crossplane-igw