apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: compositenetworks.aws.platformref.wescale.fr
  labels:
    provider: aws
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: aws.platformref.wescale.fr/v1alpha1
    kind: CompositeNetwork
  resources:
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: VPC
        spec:
          forProvider:
            region: eu-west-3
            cidrBlock: 192.168.0.0/16
            enableDnsSupport: true
            enableDnsHostNames: true
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.labels[networks.aws.platformref.wescale.fr/network-id]
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: InternetGateway
        spec:
          forProvider:
            region: eu-west-3
            vpcIdSelector:
              matchControllerRef: true
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.labels[networks.aws.platformref.wescale.fr/network-id]
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: eu-west-3a
            access: public
        spec:
          forProvider:
            region: eu-west-3
            mapPublicIPOnLaunch: true
            cidrBlock: 192.168.0.0/18
            vpcIdSelector:
              matchControllerRef: true
            availabilityZone: eu-west-3a
            tags:
              - key: kubernetes.io/role/elb
                value: "1"
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.labels[networks.aws.platformref.wescale.fr/network-id]
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: eu-west-3b
            access: public
        spec:
          forProvider:
            region: eu-west-3
            mapPublicIPOnLaunch: true
            cidrBlock: 192.168.64.0/18
            vpcIdSelector:
              matchControllerRef: true
            availabilityZone: eu-west-3b
            tags:
              - key: kubernetes.io/role/elb
                value: "1"
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.labels[networks.aws.platformref.wescale.fr/network-id]
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: eu-west-3a
            access: private
        spec:
          forProvider:
            region: eu-west-3
            cidrBlock: 192.168.128.0/18
            vpcIdSelector:
              matchControllerRef: true
            availabilityZone: eu-west-3a
            tags:
              - key: kubernetes.io/role/internal-elb
                value: "1"
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.labels[networks.aws.platformref.wescale.fr/network-id]
        
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: eu-west-3b
            access: private
        spec:
          forProvider:
            region: eu-west-3
            cidrBlock: 192.168.192.0/18
            vpcIdSelector:
              matchControllerRef: true
            availabilityZone: eu-west-3b
            tags:
              - key: kubernetes.io/role/internal-elb
                value: "1"
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.labels[networks.aws.platformref.wescale.fr/network-id]
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: RouteTable
        spec:
          forProvider:
            region: eu-west-3
            vpcIdSelector:
              matchControllerRef: true
            routes:
              - destinationCidrBlock: 0.0.0.0/0
                gatewayIdSelector:
                  matchControllerRef: true
            associations:
              - subnetIdSelector:
                  matchControllerRef: true
                  matchLabels:
                    zone: eu-west-3a
                    access: public
              - subnetIdSelector:
                  matchControllerRef: true
                  matchLabels:
                    zone: eu-west-3b
                    access: public
              - subnetIdSelector:
                  matchControllerRef: true
                  matchLabels:
                    zone: eu-west-3a
                    access: private
              - subnetIdSelector:
                  matchControllerRef: true
                  matchLabels:
                    zone: eu-west-3b
                    access: private
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.labels[networks.aws.platformref.wescale.fr/network-id]
    - base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: SecurityGroup
        spec:
          forProvider:
            region: eu-west-3
            vpcIdSelector:
              matchControllerRef: true
            groupName: platform-ref-aws-cluster
            description: Allow access to PostgreSQL
            ingress:
              - fromPort: 5432
                toPort: 5432
                ipProtocol: tcp
                ipRanges:
                  - cidrIp: 0.0.0.0/0
                    description: Everywhere
      patches:
        - fromFieldPath: spec.id
          toFieldPath: metadata.labels[networks.aws.platformref.wescale.fr/network-id]