apiVersion: aws.platformref.wescale.fr/v1alpha1
kind: Cluster
metadata:
  name: demo-aws-cluster
spec:
  id: demo-aws-cluster
  parameters:
    nodes:
      count: 3
      size: small
    services:
      operators:
        prometheus:
          version: "10.0.2"
    networkRef:
      id: demo-aws-network
  writeConnectionSecretToRef:
    name: demo-aws-cluster
