apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: rdspostgresql
spec:
  forProvider:
    region: eu-west-3
    dbSubnetGroupNameSelector:
      matchLabels:
        vpc: crossplane-vpc
        private: 'true'
    dbInstanceClass: db.t2.small
    masterUsername: masteruser
    allocatedStorage: 5
    engine: postgres
    engineVersion: "9.6"
    skipFinalSnapshotBeforeDeletion: true
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: aws-rdspostgresql-conn